export enum BUTTON_TYPES {
  ADD = 'add',
  FILTER = 'filter',
  FAB = 'fab',
  CHECK = 'check',
  FUNCTIONAL = 'functional',
  HIDE_INPUT = 'hideInput',
  GOOGLE_SIGN_IN = 'googleSignIn',
  SIGN_IN = 'signIn',
  PASSWORD_VISIBILITY = 'passwordVisibility',
  SUBMIT = 'submit',
  BACK = 'back',
  SETTING = 'setting',
  BOTTOM_SHEET_BUTTON = 'buttonSheetButton',
  WITH_ICON = 'withIcon',
}
